# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chapter4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chapter4

  target 'Chapter4Tests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'Chapter4UITests' do
    # Pods for testing
  end

end
